import React, { useState } from 'react';
import { Copy } from 'lucide-react';
import { STANDARD_JSON_OUTPUT_FORMAT } from '@/lib/constants';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';

interface PromptTemplateEditorProps {
  template?: {
    id?: string;
    name: string;
    displayName: string;
    description: string;
    userPrompt: string;
    systemPrompt?: string;
    promptType: 'system' | 'user' | 'combined';
    inputType: 'email' | 'url' | 'both';
    isSystemTemplate?: boolean;
  };
  onSave: (template: any) => Promise<void>;
  onCancel: () => void;
}

export const PromptTemplateEditor: React.FC<PromptTemplateEditorProps> = ({
  template,
  onSave,
  onCancel,
}) => {
  const isReadOnly = template?.isSystemTemplate || false;

  // Extract evaluation prompt (remove standard format if present)
  const extractEvaluationPrompt = (userPrompt?: string) => {
    if (!userPrompt) return '';
    // Remove the standard format section if it exists
    const formatIndex = userPrompt.indexOf('═══════════════════════════════════════════════════════════');
    if (formatIndex > 0) {
      return userPrompt.substring(0, formatIndex).trim();
    }
    return userPrompt;
  };

  const [formData, setFormData] = useState({
    name: template?.name || '',
    displayName: template?.displayName || '',
    description: template?.description || '',
    evaluationPrompt: extractEvaluationPrompt(template?.userPrompt),
    systemPrompt: template?.systemPrompt || '',
    promptType: template?.promptType || 'combined',
    inputType: template?.inputType || 'email',
  });

  const [showOutputFormat, setShowOutputFormat] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Combine evaluation prompt with standard output format
    const userPrompt = formData.evaluationPrompt + STANDARD_JSON_OUTPUT_FORMAT;

    await onSave({
      ...formData,
      userPrompt, // This is what gets stored in DB
    });
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Template ID (Read-Only, ONLY shown when editing existing template) */}
      {template?.id && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <div className="flex items-center justify-between">
            <div>
              <label className="block text-sm font-medium text-blue-900 mb-1">
                Template ID (Read-Only - Generated by System)
              </label>
              <div className="flex items-center gap-2">
                <code className="text-sm bg-white px-3 py-2 rounded border border-blue-300 text-gray-700 font-mono">
                  {template.id}
                </code>
                <span className="text-xs text-blue-700">
                  ⓘ This ID is generated automatically and cannot be modified
                </span>
              </div>
            </div>
            <Button
              type="button"
              size="sm"
              onClick={() => {
                navigator.clipboard.writeText(template.id!);
                alert('Template ID copied to clipboard!');
              }}
            >
              <Copy className="w-4 h-4 mr-2" />
              Copy ID
            </Button>
          </div>
        </div>
      )}

      {/* Info banner for new templates */}
      {!template?.id && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
          <div className="flex items-start gap-2">
            <span className="text-green-600 text-lg">✨</span>
            <div className="text-sm text-green-800">
              <strong>Creating New Template</strong>
              <p className="mt-1">A unique ID will be automatically generated when you save this template.</p>
            </div>
          </div>
        </div>
      )}

      {/* Read-only banner for system templates */}
      {isReadOnly && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
          <div className="flex items-start gap-2">
            <span className="text-yellow-600 text-lg">🔒</span>
            <div className="text-sm text-yellow-800">
              <strong>System Template (Read-Only)</strong>
              <p className="mt-1">This is a built-in template and cannot be modified. You can view its configuration but not edit it.</p>
            </div>
          </div>
        </div>
      )}

      {/* Basic Info Section */}
      <div className="space-y-4">
        <h3 className="text-lg font-semibold">Template Information</h3>

        <div>
          <label className="block text-sm font-medium mb-1">
            Template Name (Machine ID)
          </label>
          <Input
            type="text"
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            placeholder="e.g., custom_executive_screening"
            required
            disabled={isReadOnly}
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">
            Display Name
          </label>
          <Input
            type="text"
            value={formData.displayName}
            onChange={(e) => setFormData({ ...formData, displayName: e.target.value })}
            placeholder="e.g., Executive Screening"
            required
            disabled={isReadOnly}
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">
            Description
          </label>
          <textarea
            value={formData.description}
            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            placeholder="When to use this template, expected accuracy, etc."
            className="w-full px-3 py-2 border rounded h-20"
            required
            disabled={isReadOnly}
          />
        </div>
      </div>

      {/* System Prompt Section (Optional) */}
      <div className="space-y-4">
        <h3 className="text-lg font-semibold">System Prompt (Optional)</h3>
        <p className="text-sm text-gray-600">
          Defines the AI's role and high-level guidelines.
        </p>

        <textarea
          value={formData.systemPrompt}
          onChange={(e) => setFormData({ ...formData, systemPrompt: e.target.value })}
          placeholder="You are a senior security analyst specializing in..."
          className="w-full px-3 py-2 border rounded h-32 font-mono text-sm"
          disabled={isReadOnly}
        />
      </div>

      {/* Evaluation Criteria Section (EDITABLE) */}
      <div className="space-y-4 border-2 border-blue-500 rounded-lg p-4">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-semibold">
            📝 Evaluation Criteria (Editable)
          </h3>
          <span className="text-sm text-blue-600 font-medium">
            What to analyze
          </span>
        </div>

        <p className="text-sm text-gray-600">
          Define what factors to evaluate, what signals to look for, and how to assess risk.
          Use template variables like <code className="bg-gray-100 px-1">{'{{sender_email}}'}</code>,
          <code className="bg-gray-100 px-1">{'{{subject}}'}</code>, etc.
        </p>

        <textarea
          value={formData.evaluationPrompt}
          onChange={(e) => setFormData({ ...formData, evaluationPrompt: e.target.value })}
          placeholder={`Analyze the following email for phishing indicators:

From: {{sender_email}}
Subject: {{subject}}
Body: {{body_snippet}}

Evaluate:
1. Sender authenticity (SPF: {{spf_status}}, DKIM: {{dkim_status}})
2. Suspicious links ({{suspicious_links_summary}})
3. Credential harvesting ({{password_forms}} forms detected)
4. Urgency manipulation (Score: {{urgency_score}}/10)

Focus on...`}
          className="w-full px-3 py-2 border-2 border-blue-300 rounded h-96 font-mono text-sm"
          required
          disabled={isReadOnly}
        />

        <div className="text-xs text-gray-500">
          <details>
            <summary className="cursor-pointer font-medium">
              📚 Available Variables (click to expand)
            </summary>
            <div className="mt-2 grid grid-cols-3 gap-2 bg-gray-50 p-3 rounded max-h-64 overflow-auto">
              <code>{'{{sender_email}}'}</code>
              <code>{'{{sender_domain}}'}</code>
              <code>{'{{subject}}'}</code>
              <code>{'{{body}}'}</code>
              <code>{'{{body_snippet}}'}</code>
              <code>{'{{spf_status}}'}</code>
              <code>{'{{dkim_status}}'}</code>
              <code>{'{{dmarc_status}}'}</code>
              <code>{'{{is_role_account}}'}</code>
              <code>{'{{is_disposable}}'}</code>
              <code>{'{{suspicious_links}}'}</code>
              <code>{'{{link_count}}'}</code>
              <code>{'{{top_links}}'}</code>
              <code>{'{{urgency_score}}'}</code>
              <code>{'{{urgency_detected}}'}</code>
              <code>{'{{password_forms}}'}</code>
              <code>{'{{attachment_count}}'}</code>
              <code>{'{{qr_code_count}}'}</code>
              <code>{'{{button_count}}'}</code>
              <code>{'{{all_domains}}'}</code>
              <code>{'{{external_domains}}'}</code>
              <code>{'{{suspicious_domains}}'}</code>
            </div>
          </details>
        </div>
      </div>

      {/* Output Format Section (READ-ONLY) */}
      <div className="space-y-4 border-2 border-green-500 rounded-lg p-4 bg-green-50">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-semibold flex items-center gap-2">
            🔒 Output Format (Auto-Applied)
          </h3>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => setShowOutputFormat(!showOutputFormat)}
            className="text-green-600 hover:text-green-700"
          >
            {showOutputFormat ? 'Hide' : 'Show'} Format
          </Button>
        </div>

        <div className="flex items-start gap-2 text-sm text-gray-700">
          <span className="text-green-600">ℹ️</span>
          <p>
            This standard JSON format is <strong>automatically appended</strong> to your evaluation criteria.
            It ensures consistent, parseable output from the AI. You don't need to edit this section.
          </p>
        </div>

        {showOutputFormat && (
          <pre className="bg-white border border-green-300 rounded p-4 text-xs overflow-auto max-h-64">
            {STANDARD_JSON_OUTPUT_FORMAT}
          </pre>
        )}
      </div>

      {/* Actions */}
      <div className="flex justify-end gap-3">
        <Button
          type="button"
          variant="outline"
          onClick={onCancel}
        >
          {isReadOnly ? 'Close' : 'Cancel'}
        </Button>
        {!isReadOnly && (
          <Button type="submit">
            Save Template
          </Button>
        )}
      </div>
    </form>
  );
};
